pub const MODE_TRANSFER_AND_AUTHORITY_ARE_THE_SAME: u8 = 0b00000001;
pub const MODE_TRANSFER_AND_APPROVAL_ARE_THE_SAME: u8 = 0b00000010;
pub const MODE_PAYER_AND_SUBJECT_ARE_THE_SAME: u8 = 0b00000100;
pub const MODE_PAYMENT_AND_OFFERING_MINTS_ARE_THE_SAME: u8 = 0b00001000;
pub const MODE_PAYMENT_AND_OFFERING_TOKENS_ARE_THE_SAME: u8 = 0b00010000;

pub const INIT_PUBLISHER_MODE_PAYER_AND_AUTHORITY_ARE_THE_SAME: u8 = 0b00000001;

pub const UPDATE_PUBLISHER_MODE_PAYER_AND_AUTHORITY_ARE_THE_SAME: u8 = 0b00000001;
pub const UPDATE_PUBLISHER_MODE_AUTHORITY_AND_TRANSFER_ARE_THE_SAME: u8 = 0b00000010;
pub const UPDATE_PUBLISHER_MODE_TRANSFER_AND_APPROVAL_ARE_THE_SAME: u8 = 0b00000100;

pub const INIT_PUBLISHER_TOKEN_MODE_PAYER_AND_AUTHORITY_ARE_THE_SAME: u8 = 0b00000001;
pub const INIT_PUBLISHER_TOKEN_MODE_TOKEN_PROGRAM_AND_SYSTEM_ARE_THE_SAME: u8 = 0b00000010;

pub const INIT_OFFERING_MODE_PAYER_AND_PROMOTER_ARE_THE_SAME: u8 = 0b00000001;
pub const INIT_OFFERING_MODE_FUNDED_AND_SYSTEM_ARE_THE_SAME: u8 = 0b00000010;
pub const INIT_OFFERING_MODE_OFFERED_AND_SYSTEM_ARE_THE_SAME: u8 = 0b00000100;

pub const FINALIZE_OFFERING_MODE_PAYER_AND_PROMOTER_ARE_THE_SAME: u8 = 0b00000001;
pub const FINALIZE_OFFERING_MODE_PAYMENT_AND_SYSTEM_ARE_THE_SAME: u8 = 0b00000010;

pub const OFFERING_MODE_PAYER_AND_PROMOTER_ARE_THE_SAME: u8 = 0b00000001;
pub const OFFERING_MODE_FUNDED_AND_SYSTEM_ARE_THE_SAME: u8 = 0b00000010;

pub const INIT_PURCHASE_MODE_PAYER_AND_SUBJECT_ARE_THE_SAME: u8 = 0b00000001;
pub const INIT_PURCHASE_MODE_FUNDED_AND_SYSTEM_ARE_THE_SAME: u8 = 0b00000010;

pub const PURCHASE_MODE_PAYER_AND_SUBJECT_ARE_THE_SAME: u8 = 0b00000001;
pub const PURCHASE_MODE_FUNDED_AND_SYSTEM_ARE_THE_SAME: u8 = 0b00000010;

pub const PUBLISHER_PDA_SEED: &[u8] = &[0];
pub const PUBLISHER_TOKEN_PDA_SEED: &[u8] = &[2];
pub const OFFERING_PDA_SEED: &[u8] = &[3];
pub const PURCHASE_PDA_SEED: &[u8] = &[5];
pub const CUSTODIAL_PDA_SEED: &[u8] = &[6];

pub const UNINITIALIZED_PDA_TYPE: u8 = 0;
pub const CLOSED_PDA_TYPE: u8 = 1;
pub const PUBLISHER_PDA_TYPE: u8 = 2;
pub const PUBLISHER_TOKEN_PDA_TYPE: u8 = 3;
pub const OFFERING_PDA_TYPE: u8 = 4;
pub const PURCHASE_PDA_TYPE: u8 = 5;

pub const INITIATE_PUBLISHER_TAG: u8 = 0;
pub const UPDATE_PUBLISHER_TAG: u8 = 1;
pub const CLAIM_PUBLISHER_AUTHORITY_TAG: u8 = 2;
pub const WITHDRAW_PUBLISHER_TAG: u8 = 3;
pub const WITHDRAW_PUBLISHER_TOKEN_TAG: u8 = 4;
pub const INITIATE_OFFERING_TAG: u8 = 5;
pub const APPROVAL_OFFERING_TAG: u8 = 6;
pub const CLOSE_OFFERING_TAG: u8 = 7;
pub const INITIATE_PURCHASE_TAG: u8 = 8;
pub const REFUND_PURCHASE_TAG: u8 = 9;
pub const DISTRIBUTE_TAG: u8 = 10;
pub const INITITATE_PUBLISHER_TOKEN_TAG: u8 = 11;
pub const UPDATE_PUBLISHER_TOKEN_TAG: u8 = 12;
pub const FINALIZE_OFFERING_CREATION_TAG: u8 = 13;
pub const UPDATE_OFFERING_TARGET_TAG: u8 = 14;

pub const PUBLISHER_INITIATED_EVENT: &[u8] = &[0];
pub const PUBLISHER_UPDATED_EVENT: &[u8] = &[1];
pub const PUBLISHER_AUTHORITY_CLAIMED_EVENT: &[u8] = &[2];
pub const PUBLISHER_WITHDRAWAL_EVENT: &[u8] = &[3];
pub const PUBLISHER_TOKEN_WITHDRAWAL_EVENT: &[u8] = &[4];
pub const OFFERING_INITIATED_EVENT: &[u8] = &[5];
pub const OFFERING_APPROVAL_EVENT: &[u8] = &[6];
pub const OFFERING_CLOSED_EVENT: &[u8] = &[7];
pub const PURCHASE_INITIATED_EVENT: &[u8] = &[8];
pub const PURCHASE_ADDED_EVENT: &[u8] = &[9];
pub const PURCHASE_REFUNDED_EVENT: &[u8] = &[10];
pub const PURCHASE_DISTRIBUTION_DISTRIBUTED_EVENT: &[u8] = &[11];
pub const PUBLISHER_TOKEN_INITIATED_EVENT: &[u8] = &[12];
pub const PUBLISHER_TOKEN_UPDATED_EVENT: &[u8] = &[13];
pub const OFFERING_CREATION_FINALIZED_EVENT: &[u8] = &[14];